[2025-05-11 18:15:46.147246] 开始评估任务 user_id=xiaowang, job_id=13
使用参数文件: C:\Users\ZY\Desktop\Forecaster\config\job_config\job_params_xiaowang_13.json
[2025-05-11 18:15:46.147246] 评估失败 ❌: [Errno 2] No such file or directory: 'C:\\Users\\ZY\\Desktop\\Forecaster\\data\\user_data\\xiaowang\\test_job_data\\13\\format_test_dic_xiaowang_1_13.joblib'
详细错误信息如下：
Traceback (most recent call last):
  File "C:\Users\ZY\Desktop\Forecaster\scripts\taks_post_process.py", line 54, in <module>
    rank_score = Post_Task.execute_process()
  File "C:\Users\ZY\Desktop\Forecaster\web_interface\..\src\model_evaluator\post_process_src.py", line 98, in execute_process
    return task_mapping[task_id]()
  File "C:\Users\ZY\Desktop\Forecaster\web_interface\..\src\model_evaluator\post_process_src.py", line 50, in process_task1
    test_dic = joblib.load(
  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ZY\\Desktop\\Forecaster\\data\\user_data\\xiaowang\\test_job_data\\13\\format_test_dic_xiaowang_1_13.joblib'
